AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'config/*'
    - 'node_modules/**/*'

Layout/EmptyLines:
  Exclude:
    - 'Gemfile'

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/DotPosition:
  EnforcedStyle: trailing

Style/SymbolArray:
  EnforcedStyle: brackets

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ExpandPathArguments:
  Exclude:
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
Style/AndOr:
  Enabled: false

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

Style/StringLiterals:
  Exclude:
    - 'Gemfile'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'

Metrics/LineLength:
  Max: 80
  Exclude:
    - 'db/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'Gemfile'
    - 'Rakefile'

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'lib/modules/*'

Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'lib/modules/*'

Metrics/ClassLength:
  Max: 150

Bundler/OrderedGems:
  Enabled: false
