dist: trusty
sudo: false
language: ruby
rvm:
- 2.5.1
addons:
  postgresql: 9.6
before_install:
  - gem update --system
  - gem install bundler
before_script:
  - psql -c 'create database "cw-ndc-tracker_test"' -U postgres
  - RAILS_ENV=test bundle exec rake db:migrate
script:
  - bundle exec rspec

