apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: {name}
  name: {name}
spec:
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        name: {name}
    spec:
      tolerations:
      - key: "type"
        operator: "Equal"
        value: "webapps"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - webapps
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: name
                  operator: In
                  values:
                  - {name}
              topologyKey: kubernetes.io/hostname
      containers:
      - name: {name}
        image: vizzuality/{name}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
        env:
          - name: RACK_ENV
            value: production
          - name: RAILS_ENV
            value: production
          - name: PORT
            value: "3000"
          - name: RAILS_SERVE_STATIC_FILES
            value: "true"
          - name: PASSWORD_PROTECT
            value: "false"
          - name: RAILS_LOG_TO_STDOUT
            value: "true"
          - name: AUTH_USERNAME
            valueFrom:
              secretKeyRef:
                name: appsecrets
                key: CW_AUTH_USERNAME
          - name: AUTH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: appsecrets
                key: CW_AUTH_PASSWORD
          - name: POSTGRES_URL
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: CW_TRACKING_POSTGRES_URL
          - name: API_URL
            value: "http://ndc-tracker-staging.herokuapp.com/api/v1"
          - name: CORS_WHITELIST
            value: "http://ndc-tracker-staging.herokuapp.com"

        ports:
          - containerPort: 3000

      restartPolicy: Always
